#!/usr/bin/env python
import rospy
import cv2
from cv_bridge import CvBridge, CvBridgeError
from sensor_msgs.msg import Image
from apriltags2_ros.msg import AprilTagDetectionArray


def callback(ros_data):

    bridge = CvBridge()
    cv_image = bridge.imgmsg_to_cv2(ros_data, desired_encoding="passthrough")
    cv2.imshow('video',cv_image)
    cv2.waitKey(1)



    #image_data = bridge.cv2_to_imgmsg(frame, encoding="passthrough")
    #tag_publisher = rospy.Publisher('/camera_rect/image_rect', Image, queue_size=10)
    #image_message = Image()
    #image_message.data = image_data.data
    #tag_publisher.publish(image_message)
    #cv2.waitKey(1)


    #image_message = Image()
    #image_message.data = ros_data.data
    #tag_publisher.publish(image_message)

    #bridge = CvBridge()
    #cv_image = bridge.imgmsg_to_cv2(ros_data, "bgr8")
    #cv2.imshow('video',cv_image)
    #cv2.waitKey(1)



def listener():
    rospy.init_node('detect_tag', anonymous = True)
    rospy.Subscriber("/tag_detections_image",Image,callback)
    rospy.spin()

if __name__ == '__main__':
    listener()
